config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :theme_items
    resources :theme_boards
    resources :photo_theme_items
    resources :photo_themes
    resources :photo_achievements
    resources :categories

    root to: "users#index"
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # テーマボード
  resources :theme_boards, except: %i[edit] do
    collection do
      get :completed
    end
    member do
      get :download
    end
  end

  # お試し
  get 'trial', to: 'trials#show'
  post 'trial', to: 'trials#update'

  # 静的ページ
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  # ユーザー登録・ログイン・プロフィール
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resource :profile, only: %i[show edit update destroy]
  resources :password_resets, only: %i[new create edit update]

  # 404ページ
  get '*path', to: 'application#render_404'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login

  def top; end

  def terms; end

  def privacy_policy; end
end

app/views/static_pages/privacy_policy.html.slim
- content_for(:title, t('.title'))
h1.page-title.text-deep-sky
  span.page-title-line.border-deep-sky
    = t('.title')
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | お客様から取得する情報
  p.mb-2
    | 当サービスは、お客様から以下の情報を取得します。
  ul.list-disc.pl-6
    li.mb-1.5
      | 氏名(ニックネームやペンネームも含む)
    li.mb-1.5
      | メールアドレス
    li.mb-1.5
      | 写真や動画
    li
      | 外部サービスでお客様が利用するID、その他外部サービスのプライバシー設定によりお客様が連携先に開示を認めた情報
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | お客様の情報を利用する目的
  p.mb-2
    | 当サービスは、お客様から取得した情報を、以下の目的のために利用します。
  ul.list-disc.pl-6
    li.mb-1.5
      | 当サービスに関する登録の受付、お客様の本人確認、認証のため
    li.mb-1.5
      | お客様の当サービスの利用履歴を管理するため
    li.mb-1.5
      | 当サービスにおけるお客様の行動履歴を分析し、当サービスの維持改善に役立てるため
    li.mb-1.5
      | お客様からのお問い合わせに対応するため
    li.mb-1.5
      | 当方の規約や法令に違反する行為に対応するため
    li.mb-1.5
      | 当サービスの変更、提供中止、終了、契約解除をご連絡するため
    li.mb-1.5
      | 当方規約の変更等を通知するため
    li
      | 以上の他、当サービスの提供、維持、保護及び改善のため
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 安全管理のために講じた措置
  p
    | 当サービスが、お客様から取得した情報に関して安全管理のために講じた措置につきましては、末尾記載のお問い合わせ先にご連絡をいただきましたら、法令の定めに従い個別にご回答させていただきます。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 第三者提供
  p.mb-2
    | 当サービスは、お客様から取得する情報のうち、個人データ（個人情報保護法第２条第６項）に該当するものついては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。
  p.mb-2
    | 但し、次の場合は除きます。
  ul.list-disc.pl-6
    li.mb-1.5
      | 個人データの取扱いを外部に委託する場合
    li.mb-1.5
      | 当方や当サービスが買収された場合
    li.mb-1.5
      | 事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）
    li
      | その他、法律によって合法的に第三者提供が許されている場合
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | アクセス解析ツール
  p.mb-2
    | 当サービスは、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。トラフィックデータは匿名で収集されており、個人を特定するものではありません。Cookieを無効にすれば、これらの情報の収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。Googleアナリティクスについて、詳しくは以下からご確認ください。
  = link_to "Google アナリティクス利用規約", "https://marketingplatform.google.com/about/analytics/terms/jp/", target: :_blank, class: 'underline text-rose-600'
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | プライバシーポリシーの変更
  p
    | 当サービスは、必要に応じて、このプライバシーポリシーの内容を変更します。この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | お問い合わせ
  p
    | お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、お問い合わせフォームよりご連絡ください。
p.mb-2
  | 記載のない項目について、正当な理由に基づきお問い合わせ頂ければ遅滞なく回答いたします。
p
  | 2023年03月05日 制定

app/views/static_pages/terms.html.slim
- content_for(:title, t('.title'))
h1.page-title.text-deep-sky
  span.page-title-line.border-deep-sky
    = t('.title')

.mb-8
  p
    | この利用規約(以下、「本規約」といいます。)は、本サービス(本サイトを含むものとし、以下、特に両者を区別しません。)の利用条件を定めるものです。本規約は、本サービスを利用するすべてのユーザーに適用されます。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 本規約への同意
  p
    | ユーザーは、本サービスを利用することによって、本規約に有効かつ取り消し不能な同意をしたものとみなされます。本規約に同意しないユーザーは、本サービスをご利用いただけません。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 利用登録
  p
    | 本サービスの利用を希望する方は、本規約に同意の上、当方の定める方法によって利用登録を申請し、当方がこれを承認することによって、本サービスの利用登録をすることができます。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 登録拒否
  p.mb-2
    | 当方は、以下のいずれかの事由があると判断した場合、利用登録の申請を承認しないことがあります。当方は登録拒否の理由について一切の開示義務を負いません。
  ul.list-disc.pl-6
    li.mb-1.5
      | 虚偽の事項を届け出た場合
    li.mb-1.5
      | 本規約に違反したことがある者からの申請である場合
    li
      | その他、当方が利用登録を相当でないと判断した場合
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 未成年による利用
  p.mb-2
    | ユーザーが未成年である場合には、法定代理人の同意を得た上で、本サービスを利用してください。本サービスのご利用にあたり必要となるスマートフォンその他デバイスについても、必ず法定代理人の同意を得た上でご使用下さい。
  p
    | 法定代理人の同意を得ずに本サービスのご利用を開始したユーザーが成年に達した場合、未成年者であった間の利用行為を追認したものとみなします。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | ログイン情報の管理
  p
    | ユーザーは、自己の責任において、本サービスのログイン情報を適切に管理するものとします。ユーザーは、いかなる場合にも、ログイン情報を第三者に譲渡または貸与し、もしくは第三者と共用することはできません。当方は、ログイン情報が第三者によって使用されたことによって生じた損害につき、当方に故意又は重大な過失がある場合を除き、一切の責任を負いません。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | コンテンツのご利用
  p.mb-2
    | 当方は、ユーザーに対し、本サービスが提供する文章、画像、動画、音声、音楽、ソフトウェア、プログラム、コードその他のコンテンツについて、本サービスの利用範囲内における私的な利用を許諾します。有償コンテンツについては、当方が定める利用料金の支払が完了した場合に、本サービスの利用範囲内における私的な利用を許諾します。これは、譲渡及び再許諾できない、非独占的な利用権です。この範囲を超えて本サービスが提供するコンテンツを利用することは一切禁止します。
  p
    | 理由の如何を問わず、ユーザーが本サービスを利用する権利を失った場合、本サービスの一切のコンテンツの利用ができなくなることを、ユーザーは予め承諾するものとします。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 遅延損害金
  p
    | 当方に対する金銭債務の支払を遅滞したユーザーは、当方に対し、年14.6％の割合による遅延損害金を支払うものとします。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | ユーザーの投稿
  p.mb-2
    | ユーザーは、ユーザーの投稿に含まれる情報を送信することについて適法な権利を有していること、及びユーザーの投稿が第三者の知的財産権（著作権、特許権、実用新案権、商標権、意匠権（それらの権利を取得し、又はそれらの権利につき登録等を出願する権利を含みます。）又はアイデア、ノウハウ等をいい、以下同様とします。）、所有権その他の権利を侵害していないことについて、当方に対し表明し、保証するものとします。
  p.mb-2
    | ユーザーの投稿に関する著作権は、ユーザー自身に留保されます。当方はユーザーの投稿に関して著作権を取得することはありません。ただし、当方は、本サービスの提供、維持、改善又は本サービスのプロモーションに必要な範囲において、無償、無期限かつ地域非限定で、ユーザーの投稿を複製、翻案、自動公衆送信及びそのために必要な送信可能化をすることができるものとします。この場合、ユーザーは、当方および当方から権利を承継し又は許諾されたものに対し著作者人格権を行使しないものとします。
  p.mb-2
    | ユーザーは自己の責任において投稿のバックアップを行わなければなりません。当方は、ユーザーの投稿のバックアップを行う義務を負わないものとします。
  p.mb-2
    | ユーザーは、以下のいずれかに該当する情報を投稿してはいけません。
  ul.list-disc.pl-6
    li.mb-1.5
      | 当方又は第三者の知的財産権、肖像権、プライバシー、名誉、その他の権利又は利益を侵害する情報
    li.mb-1.5
      | ユーザーを特定可能な個人情報等を含む情報(ただし、利用登録に必要な場合等当方が求めた場合、その他当方が認めた場合を除きます。)
    li.mb-1.5
      | わいせつな表現を含む情報
    li.mb-1.5
      | 異性、同性を問わず、面識のない第三者との出会い又はわいせつな行為等を目的とする情報
    li.mb-1.5
      | 自殺、自傷行為を誘引、勧誘又は助長する表現を含む情報
    li.mb-1.5
      | 薬物·危険ドラッグの売買に関する情報又は薬物危険ドラッグの不適切な利用を助長する表現を含む情報
    li.mb-1.5
      | 宗教的行為、宗教団体、政治的活動、政治団体の宣伝又は広告に関する情報
    li.mb-1.5
      | ネットワークビジネス関連の勧誘等に関する情報
    li.mb-1.5
      | ジャンクメール、スパムメールに相当する文面を含む情報
    li.mb-1.5
      | 未成年者に悪影響を及ぼすおそれのある情報
    li.mb-1.5
      | 残虐な表現その他他人に不快感を与えるおそれのある情報
    li.mb-1.5
      | コンピュータウイルス等の不正プログラムを含む情報
    li
      | その他当方が不適切と判断する情報
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 広告の表示
  p
    | 当方は、本サービスに当方または第三者の広告を掲載することができるものとします。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 禁止事項
  ul.list-disc.pl-6
    li.mb-1.5
      | ユーザーは、本サービスの利用にあたり、以下の行為をしてはなりません。
    li.mb-1.5
      | 法令、裁判所の判決、決定若しくは命令、又は法令上拘束力のある行政措置に違反する行為又はこれらを助長する行為
    li.mb-1.5
      | 犯罪行為に関連する行為
    li.mb-1.5
      | 当方や第三者の知的財産権を侵害する行為
    li.mb-1.5
      | 当方や第三者の肖像権、プライバシー、名誉、その他の権利又は利益を侵害する行為
    li.mb-1.5
      | 当方や第三者のサーバーまたはネットワークに過度の負担をかけたり、その正常な作動を妨害する行為
    li.mb-1.5
      | 当方のサービスの運営を妨害するおそれのある行為
    li.mb-1.5
      | 不正アクセスをし、またはこれを試みる行為
    li.mb-1.5
      | 逆アセンブル、逆コンパイル、リバースエンジニアリング等によって本サービスのソースコードを解析する行為
    li.mb-1.5
      | 本サービスに接続しているシステムに権限なく不正にアクセスし又は当方設備に蓄積された情報を不正に書き換え若しくは消去する行為
    li.mb-1.5
      | 本サービスのウェブサイトやソフトウェアを複製、送信、譲渡、貸与又は改変する行為
    li.mb-1.5
      | 本サービス上のアカウント又はコンテンツを第三者に有償で貸与、譲渡、売買等をする行為
    li.mb-1.5
      | 本サービスによって得られた情報を商業的に利用する行為
    li.mb-1.5
      | 当方が意図しない方法によって本サービスに関連して利益を得ることを目的とする行為
    li.mb-1.5
      | 当方が許諾しない本サービス上での宣伝、広告、勧誘、または営業行為
    li.mb-1.5
      | 他のユーザーに関する個人情報等を収集または蓄積する行為
    li.mb-1.5
      | 違法、不正又は不当な目的を持って本サービスを利用する行為
    li.mb-1.5
      | 本サービスの他のユーザーまたはその他の第三者に不利益、損害、不快感を与える行為
    li.mb-1.5
      | 他のユーザーに成りすます行為
    li.mb-1.5
      | 他のユーザーのアカウントを利用する行為
    li.mb-1.5
      | 面識のない異性との出会いを目的とした行為
    li.mb-1.5
      | 反社会的勢力に対して直接または間接に利益を供与する行為
    li.mb-1.5
      | 公序良俗に違反する行為
    li.mb-1.5
      | 歩行中、車両運転中、その他本サービスの利用が不適切な状況又は態様において本サービスを利用する行為
    li
      | その他、当方が不適切と判断する行為
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 換金行為の禁止
  p
    | 本サービス内で取得した一切のコンテンツまたは本仮想通貨については、手段の如何を問わず、以下の取引を一切禁止します。
  ul.list-disc.pl-6
    li.mb-1.5
      | 売買
    li.mb-1.5
      | 金銭その他の対価を授受する形でのあらゆる譲渡、譲受、貸与、借用等
    li
      | その他換金行為に該当すると当社が判断する一切の行為
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 反社会的勢力の排除
  p.mb-2
    | ユーザーは、次の各号のいずれか一にも該当しないことを表明し、かつ将来にわたっても該当しないことを表明し、保証するものとします。
  ul.list-disc.pl-6
    li.mb-1.5
      | 自ら（法人その他の団体にあっては、自らの役員を含みます。）が、暴力団、暴力団員、暴力団員でなくなった時から5年を経過しない者、暴力団準構成員、暴力団関係企業、総会屋、社会運動等標ぼうゴロまたは特殊知能暴力集団等その他これらに準じる者（以下総称して「暴力団員等」といいます。）であること
    li.mb-1.5
      | ユーザーが法人その他の団体の場合にあっては、暴力団員等が経営を支配していると認められる関係を有すること
    li.mb-1.5
      | ユーザーが法人その他の団体の場合にあっては、暴力団員等が経営に実質的に関与していると認められる関係を有すること
    li.mb-1.5
      | 自らもしくは第三者の不正の利益を図る目的または第三者に損害を加える目的をもって取引を行うなど、暴力団員等を利用していると認められる関係を有すること
    li.mb-1.5
      | 暴力団員等に対して資金等を提供し、または便宜を供与するなどの関与をしていると認められる関係を有すること
    li.mb-1.5
      | ユーザーが法人その他の団体の場合にあっては、自らの役員または自らの経営に実質的に関与している者が暴力団員等と社会的に非難されるべき関係を有すること
    li.mb-1.5
      | ユーザーは、自らまたは第三者を利用して次の各号のいずれか一にでも該当する行為を行わないことを保証するものとします。
    li.mb-1.5
      | 暴力的な要求行為
    li.mb-1.5
      | 法的な責任を超えた不当な要求行為
    li.mb-1.5
      | 取引に関して、脅迫的な言動をし、または暴力を用いる行為
    li.mb-1.5
      | 風説を流布し、偽計を用い、または威力を用いて、当方の信用を毀損し、または当方の業務を妨害する行為
    li
      | その他前各号に準ずる行為
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 利用制限
  p.mb-2
    | 当方は、ユーザーが以下のいずれかに該当する場合には、事前の通知なく、ユーザーに対して、本サービスの全部もしくは一部の利用を制限し、またはユーザーとしての登録を抹消することができるものとします。当方は、本条に基づき当方が行った行為によりユーザーに生じた損害について、一切の責任を負いません。
  ul.list-disc.pl-6
    li.mb-1.5
      | 本規約のいずれかの条項に違反した場合
    li.mb-1.5
      | 登録事項に虚偽の事実があることが判明した場合
    li.mb-1.5
      | 金銭債務の不履行があった場合
    li.mb-1.5
      | 当方からの連絡に対し、相当の期間が経過しても返答がない場合
    li.mb-1.5
      | 最終のご利用日から相当期間、本サービスのご利用がない場合
    li.mb-1.5
      | 反社会的勢力等であるか、反社会的勢力等との何らかの交流若しくは関与を行っていると当方が判断した場合
    li
      | その他、当方が本サービスの利用を適当でないと判断した場合
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 本サービスの提供の停止
  p.mb-2
    | 当方は、以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。当方は、この場合にユーザーまたは第三者が被ったいかなる不利益または損害についても、一切の責任を負わないものとします。
  ul.list-disc.pl-6
    li.mb-1.5
      | 本サービスにかかるコンピュータシステムの保守点検または更新を行う場合
    li.mb-1.5
      | 地震、落雷、火災、停電、天災またはウィルスの蔓延などの不可抗力により、本サービスの提供が困難となった場合
    li.mb-1.5
      | コンピュータまたは通信回線等が事故により停止した場合
    li
      | その他、当方が本サービスの提供が困難と判断した場合
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 退会
  p
    | ユーザーは、当方の定める手続により、利用登録を抹消し、本サービスから退会できるものとします。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 保証の否認
  p
    | 当方は、本サービスや本サービスが提供するコンテンツに、システムバグや第三者の権利侵害が含まれないことを保証するものではありません。また、安全性、信頼性、正確性、完全性、有効性、特定の目的への適合性を保証するものでもありません。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 免責
  p.mb-2
    | 当方は、本サービスに関してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし、本サービスに関する当方とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合、この免責規定は適用されません。
  p.mb-2
    | 消費者契約に該当する場合であっても、当方は、当方の過失（重過失を除きます。）によってユーザーに生じた損害のうち特別の事情から生じた損害（当方またはユーザーが損害発生につき予見し、または予見し得た場合を含みます。）について、一切の責任を負いません。ユーザーと他のユーザーまたは第三者との間において生じたトラブルについても一切責任を負いません。
  p.mb-2
    | 当方は、本サービスに関してユーザーが被った損害につき、当該損害が発生した月内にユーザーが当方に支払った利用料金を超えて賠償する責任を負わないものとします。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | サービス内容の変更
  p
    | 当社は、ユーザーに通知することなく、本サービスの内容を変更したり、本サービスの提供を中止、終了することができるものとします。ユーザーは、本サービスが終了した場合、有料コンテンツを利用する一切の権利を失い、以後、当該有料コンテンツを利用できなくなることについて、あらかじめ、異議なく同意するものとします。当社は、これらによってユーザーに生じた損害について一切の責任を負いません。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 利用規約の変更
  p
    | 当方は、ユーザーに通知することなく、いつでも本規約を変更することができるものとします。変更後の本規約は、当方ウェブサイトに掲示された時点から効力を生じるものとします。本規約の変更後、本サービスの利用を継続したユーザーは、変更後の本規約に同意したものとみなします。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 個人情報の取扱い
  p
    | 本サービスの利用によって取得するユーザーの個人情報については、当方のプライバシーポリシーに従い適切に取り扱うものとします。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 通知または連絡
  p
    | ユーザーと当方との間の通知または連絡は、当方の定める方法によって行うものとします。当方は、ユーザーから、当方が別途定める方式に従った変更届け出がない限り、現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い、これらは、発信時にユーザーへ到達したものとみなします。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 権利義務の譲渡
  p
    | ユーザーは、当方の書面による事前の承諾なく、利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し、または担保に供することはできません。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 事業譲渡
  p
    | 当方は本サービスにかかる事業を他社に事業譲渡（事業譲渡、会社分割その他事業が移転するあらゆる場合を含みます。）した場合には、当該事業譲渡に伴い利用契約上の地位、本規約に基づく権利及び義務並びにユーザーの情報を当該事業譲渡の譲受人に譲渡することができるものとします。ユーザーは、かかる譲渡につき予め同意したものとみなします。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 適用関係
  p.mb-2
    | 本規約は、ユーザーと当方との間の本サービスの利用に関わる一切の関係に適用されるものとします。
  p
    | 当方は本サービスに関し、本規約のほか、ご利用にあたってのルールを定めることがあります。これらのルールは、その名称のいかんに関わらず、本規約の一部を構成するものとします。本規約がこれらのルールと矛盾する場合には、これらのルールが優先して適用されるものとします。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 分離可能性
  p
    | 本規約のいずれかの条項又はその一部が無効又は執行不能と判断された場合であっても、当該判断は他の部分に影響を及ぼさず、本規約の残りの部分は、引き続き有効かつ執行力を有するものとします。
.mb-8
  h3.text-2xl.font-medium.mb-3.border-l-8.border-deep-sky.pl-2
    | 準拠法・裁判管轄
  p.mb-2
    | 本規約の解釈にあたっては、日本法を準拠法とします。
  p
    | 本サービスに関して紛争が生じた場合には、当方の本店所在地を管轄する地方裁判所を専属的合意管轄とします。
p
  | 2023年03月05日 制定

app/views/static_pages/top.html.slim
.mt-40.mb-40.text-center.sm:flex.sm:items-center.sm:justify-center.sm:mb-8.relative.sm:mt-24
  = image_tag 'main_visual.png', class: 'absolute top-1/2 left-1/2 -translate-y-1/2 -translate-x-1/2 w-28 sm:static sm:w-1/2 sm:translate-y-0 sm:translate-x-0 sm:w-32'
  h1.text-5xl.font-semibold.text-deep-sky.inline-block.border-b-2.border-deep-sky.px-4.md:text-8xl
    | Free Theme

p.mx-auto.max-w-lg.mb-12.leading-8
  | 旅行中やお出かけをしている中で、次の予定や帰宅時間までに時間が余ってしまうことはありませんか？<br>
    そんなとき、近くの観光地を検索しても、興味がそそる目的地がなかなか見つからなかったり、調べていくうちに面倒になってしまい、気がつけば普段家でもできるスマホゲームやSNSで時間を潰している、なんて経験はないでしょうか？<br>
    「Free Theme」はそんな旅行やおでかけの余った時間に 自分(達)の代わりにお題(テーマ)を出題してくれます。<br>
    テーマを選んで、そのテーマを達成できる目的地を選んでみたり、近くを散策してみるなど、お出かけしているときならではの時間の使い方するための、お手伝いをするサービスです。<br>
    時間が余ったけど、外出先ならではの楽しみ方がしたい！と思ったときに、ぜひ遊んでみてください！

.flex.justify-center
  - if logged_in?
    = link_to t('theme_boards.new.title'), new_theme_board_path, class: 'default-btn default-btn-color'
    = link_to t('theme_boards.index.title'), theme_boards_path, class: 'default-btn default-btn-color ml-8'
  - else
    = link_to t('defaults.login'), login_path, class: 'default-btn default-btn-color'
    = link_to 'お試し', trial_path, class: 'default-btn default-btn-color ml-8'