config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :theme_items
    resources :theme_boards
    resources :photo_theme_items
    resources :photo_themes
    resources :photo_achievements
    resources :categories

    root to: "users#index"
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # テーマボード
  resources :theme_boards, except: %i[edit] do
    collection do
      get :completed
    end
    member do
      get :download
    end
  end

  # お試し
  get 'trial', to: 'trials#show'
  post 'trial', to: 'trials#update'

  # 静的ページ
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  # ユーザー登録・ログイン・プロフィール
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resource :profile, only: %i[show edit update destroy]
  resources :password_resets, only: %i[new create edit update]

  # 404ページ
  get '*path', to: 'application#render_404'
end

app/views/shared/_after_login_header.html.slim
    li.w-1/4.g-nav-box.md:ml-6.md:w-auto
      = link_to profile_path, class: 'g-nav-btn border-deep-sky md:line-under md:after:bg-default-black' do
        i.fa-solid.fa-user.fa-2xl.text-deep-sky.g-nav-icon
        span.g-nav-text
          = t('profiles.show.title')
    li.g-nav-box.w-1/4.border-l.md:border-l-0.md:ml-6.md:w-auto
      = link_to new_theme_board_path, class: 'g-nav-btn border-deep-sky md:line-under md:after:bg-default-black' do
        i.fa-solid.fa-flag.fa-2xl.text-deep-sky.g-nav-icon
        span.g-nav-text
          = t('theme_boards.new.title')
    li.g-nav-box.w-1/4.border-l.md:border-l-0.md:ml-6.md:w-auto
      = link_to theme_boards_path, class: 'g-nav-btn border-deep-sky md:line-under md:after:bg-default-black' do
        i.fa-solid.fa-rectangle-list.fa-2xl.text-deep-sky.g-nav-icon
        span.g-nav-text
          = t('theme_boards.index.title')
    li.g-nav-box.w-1/4.border-l.md:border-l-0.md:ml-6.md:w-auto
      = link_to logout_path, data: { turbo_method: :delete }, class: 'g-nav-btn border-deep-sky md:line-under md:after:bg-default-black' do
        i.fa-solid.fa-right-from-bracket.fa-2xl.text-deep-sky.g-nav-icon
        span.g-nav-text
          = t('defaults.logout')

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #id.bg-red-100.border.border-red-400.text-red-700.px-4.py-3.rounded.mb-8
    ul.list-disc.pl-4
      - object.errors.full_messages.each do |msg|
        li.font-bold
          = msg

app/views/shared/_flash_message.html.slim
- flash.each do |message_type, message|
  div class="block text-center mb-12 #{ '-mt-12' unless current_page?(root_path) }"
    - if flash[:success]
      .bg-blue-100.text-blue-700.py-4
        = message
    - if flash[:error]
      .bg-red-100.text-red-700.py-4
        = message

app/views/shared/_footer.html.slim
footer.bg-deep-sky.text-white
  ul.text-center.mb-10.md:max-w-xl.md:mx-auto.md:flex.md:justify-evenly.md:pt-10
    li
      = link_to t('static_pages.privacy_policy.title'), privacy_policy_path, class:'py-4 block border-b border-white md:hover:border-b-0 md:py-0.5'
    li
      = link_to t('static_pages.terms.title'), terms_path, class:'py-4 block border-b border-white md:hover:border-b-0 md:py-0.5'
    li
      = link_to 'お問い合わせ', 'https://docs.google.com/forms/d/e/1FAIpQLScecyBvDUEKgetmBL2S8cdWHYOQp0Ykai7Xf4mMOtn8ZIvPvw/viewform?usp=sf_link', target: :_blank, class:'py-4 block border-b border-white md:hover:border-b-0 md:py-0.5'
  small.block.text-center.pb-10
    | &copy; Free Theme

app/views/shared/_header.html.slim
header.border-b-4.border-deep-sky.mb-12
  div.flex.justify-around.py-4.px-6
    = link_to 'Free Theme', root_path, class: 'w-auto text-deep-sky font-semibold text-3xl md:w-1/3'
    ul.fixed.left-0.bottom-0.text-center.w-full.bg-white.flex.md:justify-end.md:items-center.md:static.md:w-2/3
      - if logged_in?
        = render 'shared/after_login_header'
      - else
        li.w-1/2.g-nav-box.md:w-auto
          = link_to signup_path, class: 'g-nav-btn border-deep-sky md:line-under md:after:bg-default-black' do
            i.fa-solid.fa-user-plus.fa-2xl.text-deep-sky.g-nav-icon
            span.g-nav-text
              = t('users.new.title')
        li.w-1/2.g-nav-box.border-l.md:border-l-0.md:ml-6.md:w-auto
          = link_to login_path, class: 'g-nav-btn border-deep-sky md:line-under md:after:bg-default-black' do
            i.fa-solid.fa-right-to-bracket.fa-2xl.text-deep-sky.g-nav-icon
            span.g-nav-text
              = t('defaults.login')