config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :theme_items
    resources :theme_boards
    resources :photo_theme_items
    resources :photo_themes
    resources :photo_achievements
    resources :categories

    root to: "users#index"
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # テーマボード
  resources :theme_boards, except: %i[edit] do
    collection do
      get :completed
    end
    member do
      get :download
    end
  end

  # お試し
  get 'trial', to: 'trials#show'
  post 'trial', to: 'trials#update'

  # 静的ページ
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  # ユーザー登録・ログイン・プロフィール
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resource :profile, only: %i[show edit update destroy]
  resources :password_resets, only: %i[new create edit update]

  # 404ページ
  get '*path', to: 'application#render_404'
end

app/models/theme_board.rb
class ThemeBoard < ApplicationRecord
  belongs_to :user
  belongs_to :themeable, polymorphic: true
  has_one :photo_achievement, dependent: :destroy

  scope :unachieved_boards, -> { where(complete: false) }

  def self.set_photo_theme(id, passed_user_id)
    # id(カテゴリ)があれば該当カテゴリでランダムに取得して代入
    # idがなければ全体でランダムに取得して代入
    theme = id.present? ? PhotoTheme.where(category_id: id).sample : PhotoTheme.all.sample
    theme.theme_boards.create!(user_id: passed_user_id)
  end

  def image_judgement(image, processing)
    # 該当テーマの答えを配列で取得
    items = themeable.theme_items.pluck(:subject)
    # アップロードした画像のラベルを配列で取得(API)
    labels = Vision.get_image_data(image.path)
    # labelsの中にitemsの要素がすべて含まれているか？
    if items.to_set.subset?(labels.to_set)
      image = image_resize(image)
      # processingがtrueであればタイトルを埋め込む
      image = embedding(image) if processing.present?
      # 判定が通れば画像を保存し、ステータスを更新
      PhotoAchievement.create(theme_board_id: id, content: image)
      update(complete: true)
    else
      false
    end
  end

  # お試しテーマボードの作成
  def self.trial_theme_board_create(user, trial_content)
    trial_board = PhotoTheme.find(5).theme_boards.create(user_id: user.id, complete: true)
    PhotoAchievement.create(theme_board_id: trial_board.id, content: trial_content)
  end

  # 画像リサイズ
  def image_resize(image)
    require "image_processing/mini_magick"
    ImageProcessing::MiniMagick.source(image.tempfile).resize_to_limit(1920, 1920).call
  end

  # タイトルの埋め込み処理
  def embedding(image)
    require 'mini_magick'
    base_image = MiniMagick::Image.open(image.path.to_s)
    base_image.combine_options do |config|
      config.font './app/assets/fonts/MPLUS1-SemiBold.ttf'.freeze
      config.fill '#333333'
      config.gravity 'SouthWest'
      config.undercolor "rgba(255, 255, 255, 0.5)"
      config.pointsize (base_image[:width] * 0.05).to_i
      config.draw "text 20,20 ' テーマ：#{themeable.target}を撮影しよう '"
    end
  end
end

app/controllers/admin/theme_boards_controller.rb
module Admin
  class ThemeBoardsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/theme_boards_controller.rb
class ThemeBoardsController < ApplicationController
  skip_before_action :require_login, only: %i[show]
  before_action :set_category, only: %i[index new completed]
  before_action :set_theme_board, only: %i[show update destroy]
  before_action :unauthorised_user, only: %i[update destroy]
  before_action :acceptable_if_complete, only: %i[show]

  def index
    @theme_boards = if (category_id = params[:category_id])
                      theme_ids = with_category(category_id)
                      current_user.theme_boards.includes(:user).where(themeable_id: theme_ids, complete: false).order(created_at: :desc).page(params[:page])
                    else
                      current_user.theme_boards.includes(:user).where(complete: false).order(created_at: :desc).page(params[:page])
                    end
  end

  def show
    @theme = @theme_board.themeable
  end

  def new; end

  def create
    theme_board = ThemeBoard.set_photo_theme(params[:category_id], current_user.id)
    redirect_to theme_board, success: t('.success')
  end

  def update
    valid_params?(params[:theme_board]) and return
    if @theme_board.image_judgement(theme_board_params[:content], theme_board_params[:embedded])
      redirect_to @theme_board, success: t('.success')
    else
      redirect_to @theme_board, error: t('.fail_to_judge')
    end
  end

  def destroy
    @theme_board.destroy!
    redirect_to theme_boards_path, success: t('.success')
  end

  def completed
    @theme_boards = if (category_id = params[:category_id])
                      theme_ids = with_category(category_id)
                      current_user.theme_boards.includes(:user).where(themeable_id: theme_ids, complete: true).order(created_at: :desc).page(params[:page])
                    else
                      current_user.theme_boards.includes(:user).where(complete: true).order(created_at: :desc).page(params[:page])
                    end
  end

  def download
    @achievement = ThemeBoard.find(params[:id]).photo_achievement
    url = what_environment(@achievement)
    send_data url.read, disposition: 'attachment', type: @achievement.content.content_type, filename: @achievement.content_identifier
  end

  private

  def with_category(category_id)
    Category.find(category_id).photo_themes.includes(:category).pluck(:id)
  end

  def theme_board_params
    params.require(:theme_board).permit(:content, :embedded)
  end

  def set_theme_board
    @theme_board = ThemeBoard.find(params[:id])
  end

  def set_category
    @categories = Category.all
  end

  def unauthorised_user
    redirect_to theme_boards_path, error: t('defaults.invalid_access') unless current_user.id == @theme_board.user_id
  end

  def valid_params?(theme)
    if theme.nil?
      redirect_to @theme_board, error: t('.content_empty')
    elsif !theme[:content].content_type.in?('image/jpeg image/png image/gif')
      redirect_to @theme_board, error: t('.invalid_image_type')
    end
  end

  def what_environment(file)
    if Rails.env.production?
      URI.parse(file.content_url)
    else
      File.open(file.content.path)
    end
  end

  def acceptable_if_complete
    if @theme_board.complete == false
      if logged_in? == false
        redirect_to theme_boards_path, error: t('defaults.invalid_access')
      else
        unauthorised_user
      end
    end
  end
end

app/views/theme_boards/_after_complete_show.html.slim
.mb-8
  = image_tag "#{theme_board.photo_achievement.content}", width: "300", class: "block mx-auto mb-6"
  - if logged_in? == true
    - if current_user.id == @theme_board.user_id
      = link_to 'ダウンロード', download_theme_board_path(theme_board), class: 'default-btn default-btn-color inline-block mb-6'
      p
        = link_to("https://twitter.com/share?url=#{request.url}&text=%0a%0a「テーマ：#{@theme.target}を撮影しよう」を達成!!", title: 'Twitter', target: '_blank', class: 'border border-twitter p-2 m-auto text-twitter rounded-full hover:bg-twitter hover:text-white') do
          i.fa-brands.fa-twitter.pl-2
          span.px-2
            | Twitterに共有
        ul.mt-8
          li
            = link_to t('defaults.theme_delete'), theme_board_path, data: { turbo_method: :delete }

    - else
      p.text-center.mb-4
        | #{current_user.name}さんもテーマを達成して、画像をシェアしよう！
      = link_to "#{t('theme_boards.new.title')}はこちら", new_theme_board_path
  - else
    p.text-center.mb-2
      | 会員登録をしてテーマにチャレンジしよう！
    p.text-center
      = link_to "#{t('users.new.title')}はこちら", signup_path

app/views/theme_boards/_before_complete_show.html.slim
.mb-8
  = form_with model: theme_board do |f|
    .mb-6.max-w-xs.mx-auto
      = f.file_field :content, class: 'w-full'
    .mb-6.max-w-xs.mx-auto.text-sm
      = f.check_box :embedded, {}, true, false
      = f.label "テーマタイトルを画像に埋め込む", class: 'pl-2'
    = f.button type: 'submit', class: 'group default-btn default-btn-color cursor-pointer' do
      span class="block group-disabled:hidden"
        = t('defaults.judgement')
      span class="hidden group-disabled:block"
        = t('defaults.under_judgement')
ul
  li
    = link_to t('defaults.theme_retire'), theme_board_path, data: { turbo_method: :delete }

app/views/theme_boards/_theme_board.html.slim
  li.border-b.first:border-t
    = link_to theme_board, class: "block py-6 text-sm font" do
      span class="font-normal mx-6 text-gray-500"
        = l theme_board.created_at
      span class="font-mono py-1 px-2 border-2 border-deep-sky tracking-widest mr-6 rounded-md"
        = theme_board.themeable.category.name
      = "#{theme_board.themeable.target}を撮影しよう"

app/views/theme_boards/completed.html.slim
- content_for(:title, t('.title'))
h1.page-title.text-deep-sky
  span.page-title-line.border-deep-sky
    = t('.title')

.font-bold.mb-8
  ul.flex.text-center.justify-center.text-white.mb-8
    li.w-full.bg-gray-300.rounded-md
      = link_to '受注中', theme_boards_path, class: 'block py-2'
    li.w-full.bg-amber-300.rounded-md.ml-6
      = link_to '達成済', completed_theme_boards_path, class: 'block py-2'
  = turbo_frame_tag "theme_board_list" do
    ul.flex.flex-wrap
      - @categories.each do |category|
        li.w-1/4.mb-6.sm:w-1/6
          = button_to category.name, completed_theme_boards_path, {method: :get, class: 'default-btn block default-btn-color py-5 mx-auto font-bold text-deep-sky', params: {category_id: category.id} }
    .mb-8
      - if @theme_boards.present?
        ul
          = render @theme_boards
      - else
        p.text-center.mt-8
          = t('.no_result_achievement')
    = paginate @theme_boards
= link_to 'テーマを作成する', new_theme_board_path, class: 'block text-center m-auto mb-6 bg-deep-sky py-5 rounded-md text-white'

app/views/theme_boards/index.html.slim
- content_for(:title, t('.title'))
h1.page-title.text-deep-sky
  span.page-title-line.border-deep-sky
    = t('.title')

.font-bold.mb-8
  ul.flex.text-center.justify-center.text-white.mb-8
    li.w-full.bg-amber-300.rounded-md
      = link_to '受注中', theme_boards_path, class: 'block py-2'
    li.w-full.bg-gray-300.rounded-md.ml-6
      = link_to '達成済', completed_theme_boards_path, class: 'block py-2'
  = turbo_frame_tag "theme_board_list" do
    ul.flex.flex-wrap
      - @categories.each do |category|
        li.w-1/4.mb-6.sm:w-1/6
          = button_to category.name, theme_boards_path, {method: :get, class: 'default-btn block default-btn-color py-5 mx-auto font-bold text-deep-sky', params: {category_id: category.id} }
    .mb-8
      - if @theme_boards.present?
        ul
          = render @theme_boards
      - else
        p.text-center.mt-8
          = t('.no_result_unachieved')
    = paginate @theme_boards
= link_to 'テーマを作成する', new_theme_board_path, class: 'block text-center m-auto mb-6 bg-deep-sky py-3 rounded-md text-white'

app/views/theme_boards/new.html.slim
- content_for(:title, t('.title'))
h1.page-title.text-deep-sky
  span.page-title-line.border-deep-sky
    = t('.title')
.max-w-sm.mx-auto
  .mb-10
    h3.mb-4.font-bold.text-lg
      | ランダムでテーマを作成
    = button_to 'ランダムでテーマを作成', theme_boards_path, data: { turbo_method: :post }, class: 'default-btn default-btn-color w-11/12 mx-auto block font-bold text-deep-sky py-4'
  .mb-10
    h3.mb-4.font-bold.text-lg
      | テーマを選択して作成
    ul.flex.flex-wrap
      - @categories.each do |category|
        li.w-1/4.mb-6
          = button_to category.name, theme_boards_path, { method: :post, class: 'default-btn block default-btn-color py-5 mx-auto font-bold text-deep-sky', params: {category_id: category.id} }

app/views/theme_boards/show.html.slim
- unless @theme_board.complete == false
  - set_meta_tags og: { image: @theme_board.photo_achievement.content.url }, twitter: { image: @theme_board.photo_achievement.content.url }
- content_for(:title, @theme.target)

h1.page-title.text-deep-sky
  - if @theme_board.complete == true
    span.text-white.bg-deep-sky.rounded-full.text-sm.block.w-1/4.py-1.mx-auto.mb-3.tracking-wider
      | Complete!
  - else
    span.text-lg.block.w-1/4.mx-auto.mb-3.tracking-wider
      | Theme
  span.page-title-line.border-deep-sky
    = "#{@theme.target}を撮影しよう"

.text-center
  - if @theme_board.complete == false
    = render 'theme_boards/before_complete_show', theme_board: @theme_board
  - else
    = render 'theme_boards/after_complete_show',
    theme_board: @theme_board