config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :theme_items
    resources :theme_boards
    resources :photo_theme_items
    resources :photo_themes
    resources :photo_achievements
    resources :categories

    root to: "users#index"
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # テーマボード
  resources :theme_boards, except: %i[edit] do
    collection do
      get :completed
    end
    member do
      get :download
    end
  end

  # お試し
  get 'trial', to: 'trials#show'
  post 'trial', to: 'trials#update'

  # 静的ページ
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  # ユーザー登録・ログイン・プロフィール
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resource :profile, only: %i[show edit update destroy]
  resources :password_resets, only: %i[new create edit update]

  # 404ページ
  get '*path', to: 'application#render_404'
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  before_action :require_not_logged_in, only: %i[new create]
  before_action :not_temporary_account, only: %i[create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to theme_boards_path, success: t('.success')
    else
      flash.now[:error] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to login_path, success: t('.success')
  end

  private

  def not_temporary_account
    user = User.find_by(email: params[:email])
    if user&.temporary == true
      flash.now[:error] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end
end

app/views/user_sessions/_form.html.slim
= form_with url: login_path, data: {turbo: false} do |f|
  .mb-6
    label.label
      = User.human_attribute_name('email')
    = f.text_field :email, class: 'input_field  bg-gray-200'
  .mb-6
    label.label
      = User.human_attribute_name('password')
    = f.password_field :password, class: 'input_field bg-gray-200'
  .mb-6.text-center
    = f.submit t('defaults.login'), class: 'default-btn default-btn-color cursor-pointer'
ul.text-center
  li.mb-2
    = link_to "#{t('users.new.title')}はこちら", signup_path, class: 'line-under  after:bg-default-black'
  li
    = link_to "パスワードをお忘れの方はこちら", new_password_reset_path, class: 'line-under  after:bg-default-black'

app/views/user_sessions/new.html.slim
- content_for(:title, t('.title'))
h1.page-title.text-deep-sky
  span.page-title-line.border-deep-sky
    = t('.title')
= render 'form'